/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(symbolrate.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(496be8518459dcb01aadb64a9e9dab79)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <symbolrate/symbolrate.h>
// pydoc.h is automatically generated in the build directory
#include <symbolrate_pydoc.h>

void bind_symbolrate(py::module& m)
{

    using symbolrate    = ::gr::symbolrate::symbolrate;


    py::class_<symbolrate, gr::block, gr::basic_block,
        std::shared_ptr<symbolrate>>(m, "symbolrate", D(symbolrate))

        .def(py::init(&symbolrate::make),
           py::arg("samp_rate"),
           py::arg("valid_min"),
           py::arg("valid_max"),
           py::arg("logRates"),
           D(symbolrate,make)
        )
        



        ;




}








